name: My GitHub Actions Workflow

on:
  push:
    branches:
      - main
    paths:
      - 'microservice1/**'

jobs:
  build-and-deploy-ServiceRegistry:
    if: github.event_path == 'microservice1/*' # Use the specific path of the file that triggers this job
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          ref: ${{ github.event.inputs.branch }}

      - name: Build and push Docker image for ServiceRegistry
        run: |
          echo Build started on $(date)
          TAG="image_$(date +'%Y%m%d_%H%M%S')"
          echo Building the Docker image with tag $TAG...
          docker build -t dev-microservices:$TAG ./microservice1
