name: My GitHub Actions Workflow

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy-microservice1:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Check for changes in microservice1
        id: check_changes_microservice1
        run: |
          # Get the list of changed files
          CHANGED_FILES=$(git diff --name-only HEAD^ HEAD)

          # Check if any file in microservice1 is changed
          if [[ $CHANGED_FILES == *"microservice1/"* ]]; then
            echo "Changes detected in microservice1"
            echo ::set-output name=files::true
          else
            echo "No changes detected in microservice1"
            echo ::set-output name=files::false
          fi

      - name: Build and push Docker image for microservice1
        if: steps.check_changes_microservice1.outputs.files == 'true'
        run: |
          echo Build started on $(date)
          TAG="image_$(date +'%Y%m%d_%H%M%S')"
          echo Building the Docker image with tag $TAG...
          docker build -t dev-microservices-microservice1:$TAG ./microservice1

# Add a similar job for microservice2
