name: My GitHub Actions Workflow

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Check for changes
        id: check_changes
        run: |
          CHANGED_FILES=$(git diff --name-only ${{ github.event.before }} ${{ github.sha }})
          echo "::set-output name=changes::${CHANGED_FILES}"

      - name: Build and deploy
        run: |
          CHANGED_FILES="${{ steps.check_changes.outputs.changes }}"
          
          if [[ $CHANGED_FILES == *'microservice1/'* ]]; then
            echo "Changes detected in microservice1, building and deploying..."
            TAG="image_$(date +'%Y%m%d_%H%M%S')"
            echo Building the Docker image with tag $TAG...
            docker build -t dev-microservices-microservice1:$TAG ./microservice1
            # Add your deployment steps for microservice1 here
          fi

          if [[ $CHANGED_FILES == *'microservice2/'* ]]; then
            echo "Changes detected in microservice2, building and deploying..."
            TAG="image_$(date +'%Y%m%d_%H%M%S')"
            echo Building the Docker image with tag $TAG...
            docker build -t dev-microservices-microservice2:$TAG ./microservice2
            # Add your deployment steps for microservice2 here
          fi
