name: My GitHub Actions Workflow

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy-microservice1:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
          submodules: 'recursive'

      - name: Check for changes in folders
        id: check_changes
        run: |
          # Get the list of changed folders using Git diff
          CHANGED_FOLDERS=$(git diff --name-only HEAD HEAD~ | xargs -I {} dirname {} | sort -u)
          # Output the list of changed folders
          echo "Changed folders:"
          for folder in $CHANGED_FOLDERS; do
            echo "- $folder"
          done

      - name: Build and push Docker image for microservice1
        if: contains('${{ steps.check_changes.outputs.CHANGED_FOLDERS }}', 'microservice1') &&
            !contains('${{ steps.check_changes.outputs.CHANGED_FOLDERS }}', 'microservice2')
        run: |
          echo "$CHANGED_FOLDERS"
          echo Build started on $(date)
          TAG="image_$(date +'%Y%m%d_%H%M%S')"
          echo Building the Docker image with tag $TAG...
          docker build -t dev-microservices-microservice1:$TAG ./microservice1
