name: My GitHub Actions Workflow

on:
  push:
    branches:
      - main

jobs:
  # JOB to run change detection
  changes:
    runs-on: ubuntu-latest
    # Required permissions
    # Set job outputs to values from filter step
    outputs:
      microservice1: ${{ steps.filter.outputs.microservice1 }}
      microservice2: ${{ steps.filter.outputs.microservice2 }}
    steps:
    - uses: actions/checkout@v3
    # For pull requests, it's not necessary to checkout the code
    - uses: dorny/paths-filter@v2
      id: filter
      with:
        filters: |
          microservice1:
            - 'microservice1/**'
          microservice2:
            - 'microservice2/**'

  # JOB to check the changes in ServiceRegistry code
  ServiceRegistry:
    needs: changes
    if: ${{ needs.changes.outputs.ServiceRegistry == 'true' }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up AWS CLI forabc
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1

      - name: Login to ECR for ServiceRegistry
        run: aws ecr get-login-password --region us-east-1 | docker login --username AWS --password-stdin 466471976337.dkr.ecr.us-east-1.amazonaws.com

      - name: Build and Push ServiceRegistry 
        run: |
          echo Build started on $(date)
          TAG="image_$(date +'%Y%m%d_%H%M%S')"
          echo Building the Docker image with tag $TAG...
          docker build -t dev-microservices-service-registry:$TAG ./ServiceRegistry
          docker tag dev-microservices-service-registry:$TAG 466471976337.dkr.ecr.us-east-1.amazonaws.com/dev-microservices-service-registry:$TAG
          docker push 466471976337.dkr.ecr.us-east-1.amazonaws.com/dev-microservices-service-registry:$TAG

  # JOB to check the changes in MainService code
  MainService:
    needs: changes
    if: ${{ needs.changes.outputs.MainService == 'true' }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up AWS CLI for MainService
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1

      - name: Login to ECR for MainService
        run: aws ecr get-login-password --region us-east-1 | docker login --username AWS --password-stdin 466471976337.dkr.ecr.us-east-1.amazonaws.com

      - name: Build and Push MainService
        run: |
          echo Build started on $(date)
          TAG="image_$(date +'%Y%m%d_%H%M%S')"
          echo Building the Docker image with tag $TAG...
          docker build -t dev-microservices-main-service:$TAG ./MainService
          docker tag dev-microservices-main-service:$TAG 466471976337.dkr.ecr.us-east-1.amazonaws.com
          docker push 466471976337.dkr.ecr.us-east-1.amazonaws.com/dev-microservices-main-service:$TAG
