name: My GitHub Actions Workflow

on:
  push:
    branches:
      - main
    paths:
      - 'microservice1/**'
      - 'microservice2/**'  # Watch for changes in the microservice2 folder and its subdirectories

jobs:
  build-and-deploy-microservice1:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Build and push Docker image for microservice1
        run: |
          echo Build started on $(date)
          TAG="image_$(date +'%Y%m%d_%H%M%S')"
          echo Building the Docker image with tag $TAG...
          docker build -t dev-microservices:$TAG ./microservice1

  build-and-deploy-microservice2:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Build and push Docker image for microservice2
        run: |
          echo Build started on $(date)
          TAG="image_$(date +'%Y%m%d_%H%M%S')"
          echo Building the Docker image with tag $TAG...
          docker build -t dev-microservices:$TAG ./microservice2
